name: dio_http_cache_extended
description: http cache lib for Flutter dio, extended from original flutter_http_cache to add cached data datetime.
version: 1.1.0
homepage: https://github.com/omidh28/dio-http-cache-extended

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^2.0.3
  json_serializable: ^3.0.0
  json_annotation: ^3.0.0
  dio: ^3.0.1
  sqflite: ^1.1.6+3
  path: ^1.6.2
  crypto: ^2.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.6

flutter:
  module:
    androidX: true
